version: '2'
services:
  web:
    image: "mingqianye/votable-api:latest"
    restart: always
    container_name: votable-api
    ports:
      - 8080:8080
    depends_on:
      - neo4j
    links:
      - neo4j
    volumes:
      - /log:/app/log
  neo4j:
    image: "neo4j:3.0.6-enterprise"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /data:/data
